### ISSUE TITLE
Pop up triggers background focus for modals

### ISSUE THREAD

**Issue by jsmorabito** [nothingislost/obsidian-workspaces-plus#30]
@nothingislost not sure if this is in your power or for individual theme makers but the pop up is being treated as a modal and being focused on when that's not necessary for just a drop down/pop up. Im referring to the blue tint covering the rest of the screen

see yin yang
<img width="638" alt="image" src="https://user-images.githubusercontent.com/46250921/132960332-a4cd5298-6263-4628-95f0-bd9472f11ed8.png">

**Comment by nothingislost** [comment]
Yeah, this is a Yin Yang thing. She's setting an !important on the modal container background. I try not to put any importants on anything if I can avoid it, so I can't override it. Ideally, there should be no background on the modal-container, the background goes on .modal-bg which I'm setting to transparent.

```css
/* from Yin&Yang */
.modal-container {
    background-color: rgb(75, 155, 255, 0.1) !important;
}
```
