### ISSUE TITLE
Compact Workspace Picker interface

### ISSUE THREAD

**Issue by jsmorabito** [nothingislost/obsidian-workspaces-plus#38]
A more compact design would make it easier to scan the list of workspaces

**Comment by nothingislost** [comment]
Details needed

**Comment by jsmorabito** [comment]
I noticed on safari that the tab group picker and other drop downs are styled like MacOS contextual menus which made me realize that our workspace picker is styled like a more spacious modal (since its been adapted from the modal)

![image](https://user-images.githubusercontent.com/46250921/134696192-222cb4d0-f7b0-4b8f-a483-4ae53ef6ddf4.png)
^safari tab picker and macOS context menus

This design pattern makes sense to me so I think we could use it for our picker ie style the workspace picker with the default context menu styling. We can make the search field more discrete as well by copying something like raycast:
![image](https://user-images.githubusercontent.com/46250921/134696844-52984f05-a40b-4d11-a059-4b49e7a86a48.png)

The result would look something like this:
![image](https://user-images.githubusercontent.com/46250921/134697262-7f592772-93f9-40d1-827e-a5441235fb5c.png)

With less spacing between the items in the menu it will be easier to scan the list of workspaces with your eyes

**Comment by nothingislost** [comment]
Context menus don't have search boxes. At least none that I can think of. So, the fuzzy search modal is still the right approach here. That end result is very close to the way it already looks though :) 
![image](https://user-images.githubusercontent.com/89109712/134731158-f40a1e03-db33-450e-9ea2-52dfcfb0b2a9.png)

You've removed some padding from the sides and top but other than that, it's pretty close. I feel we can leave the styling of the element to the theme designers. In the mean time, I can create a CSS snippet that would make the modal look fairly close to your image.

**Comment by jsmorabito** [comment]
that would be awesome! im very curious to see how much of a difference It makes especially considering how many workspaces I have haha

**Comment by nothingislost** [comment]
This looks pretty close: 
![image](https://user-images.githubusercontent.com/89109712/134824959-2720404c-7b36-4278-a7df-ed5cb6b71705.png)

and here's the CSS snippet

```css

.workspaces-plus-modal {
  padding: 0px;
  border-radius: 5px;
}

.workspaces-plus-modal .workspace-item {
  padding-left: 2em;
  padding-right: 4em;
  font-size: 0.9em;
}

.workspaces-plus-modal .prompt-results {
  padding-top: 0;
}

.workspaces-plus-modal .prompt-results::-webkit-scrollbar {
  display: none;
}

.workspaces-plus-modal .workspace-results {
  padding: 0px;
}

.workspaces-plus-modal .workspace-item.is-selected {
  border-radius: 0px !important;
}

.workspaces-plus-modal input.prompt-input {
  font-size: 0.9em;
  padding: 0px 1em;
  border-top-left-radius: 5px !important;
  border-top-right-radius: 5px !important;
  border-radius: 0px;
  border: none !important;
  border-bottom: 1px solid var(--background-modifier-border) !important;
}

.workspaces-plus-modal input.prompt-input:focus {
  box-shadow: none;
  border: none !important;
  border-bottom: 1px solid var(--background-modifier-border) !important;
}

.workspaces-plus-modal .delete-workspace {
  right: 0.7em !important;
}

.workspaces-plus-modal .rename-workspace {
  right: 2em !important;
}
```
