### ISSUE TITLE
How would I hide the status bar icon/part

### ISSUE THREAD

**Issue by ReaderGuy42** [nothingislost/obsidian-workspaces-plus#68]
Is there a way to hide the plugin part of the status bar, so I'd only access the plugin functions via the Ctrl+P?

Thanks!

**Comment by nothingislost** [comment]
For now, you can do this with a CSS snippet:
```css
.status-bar-item.plugin-workspaces-plus { display: none }
```
